### ISSUE TITLE
Property-tax exempt parcels 

### ISSUE THREAD

**Issue by framoutar** [ccao-data/public#12]
### General description

Hello - 

I am requesting a dataset of parcels with property tax-exempt status across all of Cook County per tax year, from Tax Year 2000-2021, with geographic coordinates and addresses. The data from Tax Year 2022-2023 is already available online at the following link: https://datacatalog.cookcountyil.gov/Property-Taxation/Assessor-Property-Tax-Exempt-Parcels/vgzx-68gb.

Thank you for considering this request!

Fern

### Use case

I will use the owner name and longitude/latitude (along with other variables when necessary) to identify and map out parcels owned by various city and county departments and certain types of non-profit organizations over time.

### Universe

Dataset of parcels with property tax-exempt status across all of Cook County per tax year, from Tax Year 2000-2021, with geographic coordinates and addresses.

### Unit of observation

Individual Property Identification Numbers (PINs)

### Restrictions and exclusions

n/a

### Data delivery format

Open Data asset

### Citation and use of Assessor data

- [X] I agree to the above terms.

**Comment by wrridgeway** [comment]
This is something our legacy team will need to generate and Van is OoO till 12/1, so I'd check back in around then.

**Comment by wrridgeway** [comment]
@framoutar I've reached out to Van and they don't know where this data is but are asking around.

**Comment by framoutar** [comment]
@wrridgeway Sorry for the slow reply! Thank you for coordinating - I really appreciate your and Van's help with this.

**Comment by wrridgeway** [comment]
@framoutar 

Take a look [here](https://ccao-data-public-us-east-1.s3.amazonaws.com/pdr-issue-0012.xlsx) and let us know if this data/format suffices.

**Comment by framoutar** [comment]
@wrridgeway thanks for sharing! would it be possible to include the version of the variable `owner_name` that is found in the [2022-23 version](https://datacatalog.cookcountyil.gov/Property-Taxation/Assessor-Property-Tax-Exempt-Parcels/vgzx-68gb/about_data) of the data? right now the closest variable is `mail_address_name` but it's "EXEMPT" for the majority of the parcels

**Comment by wrridgeway** [comment]
`owner_name` and `mail_address_name` are actually fed by the same column, but it seems to only be useful for 2022-2023. I'm not sure how it's being populated, but i'll try to figure it out.

**Comment by framoutar** [comment]
@wrridgeway thank you! really appreciate you looking into it. please let me know if there's some way i can be helpful

**Comment by framoutar** [comment]
hey @wrridgeway happy new new year! i hope you're doing well over there. i'm just following up to see if you've had any luck figuring out how `owner_name` is being populated? do you think it'll be possible to include the version with actual names (rather than just the phrase "EXEMPT") in the dataset for years 2000-2021?

**Comment by wrridgeway** [comment]
I tried, but I was not able to figure out where to find owner names for historical exempt parcels. It's possible the clerk has that information. Our legacy team confirmed that I was already working with the only data available, and that's the data with "Exempt" for owner name for class 0. I'm sorry, but I don't think our office has the data you're looking for.

You could try FOI'ing the office and see if the legacy team manages to find the data when they're legally compelled to, but I'm not sure the chances of that are great.

**Comment by framoutar** [comment]
thanks @wrridgeway - that all makes sense. i really appreciate the time and effort you took to try and figure this out. i'll figure out a workaround and follow up with the legacy team if it makes sense

**Comment by framoutar** [comment]
i'm not actually sure if i was supposed to "close" the issue or leave that to you! anyways - take care and thanks again!
