### ISSUE TITLE
Unit Counts and Characteristics for Small to Medium Multifamily Properties (Non-Condo Buildings with 2 to 50 Units)

### ISSUE THREAD

**Issue by Matt-PoliSci** [ccao-data/public#16]
### General description

I'm looking for a dataset similar to the "Assessor - Single and Multi-Family Improvement Characteristics" and "Assessor - Residential Condominium Unit Characteristics", but for multi-family properties that range from 2 to 50 units. I would like the dataset to include the PIN for each property, a unit count specifying how many units are in the parcel, and then physical and finish characteristics (year built, recent renovation, heating type, etc).  Essentially another version of those assessor characteristics data, but for multifamily properties larger than the ones include in the current multi-family dataset. I'll be combining that dataset with the parcel universe and parcel address datasets to do some data analysis in R.

### Use case

I work as a data analyst for Enterprise Community Partners, as a part of our Policy Development & Research team. I will be doing some analysis on inventory and ownership characteristics of unsubsidized small to medium multifamily (2-49 unit buildings) properties to support our Preservation Next program (https://preservation-next.enterprisecommunity.org/). I will be identifying patterns in both the types of SMMF buildings that exists in Cook County and will also use owner names and mailing addresses to recalculate ownership portfolios. Using those owner portfolios of multifamily properties, I will identify patterns in how different types of owners own different subsets of multifamily properties in Cook County. I will be doing this analysis using R. 

### Universe

All multi-family PINs in Cook County + corresponding assessor data on building characteristics. 

### Unit of observation

Individual Personal Identifying number (PINS) for all multifamily properties in Cook County. Essentially any multi-family property that is not in the other assessor datasets for single-family, small-multifamily, and condos. 

### Restrictions and exclusions

For this I need multifamily properties ranging from 2 to 50 units, though if data is included on multifamily buildings with larger sizes, that is fine as well. For this project, condo buildings are not categorized as multi-family. That means these buildings are owned by a single owner, generally renting out individual units. For this project I only need properties from the last few years (2022 & 2023), but if it is not a large lift, it would interesting to conduct this analysis across older years too.

### Data delivery format

Open Data asset

### Citation and use of Assessor data

- [X] I agree to the above terms.

**Comment by Matt-PoliSci** [comment]
Hi I was wondering if there are any potential updates on this data request?

**Comment by wrridgeway** [comment]
> Matt,
> 
> The closest we're going to get to something like this is already on the open data portal [here](https://datacatalog.cookcountyil.gov/Property-Taxation/Assessor-Commercial-Valuation-Data/csik-bsws/about_data). 300 class are valued by our commercial valuations team which stores its data differently than the residential team does, and values parcels using an income approach rather than a market value approach; it doesn't have an interest in collecting all of the same data we capture for residential parcels because of this.

Thank you for the speedy response. I didn't realize that 300 class multifamily properties would be included with the commercial data. Unfortunately, I'm skeptical that the commercial dataset is adequate for this project.

Just looking at the last few years, I noticed that the commercial dataset does not include the vast majority of the 300 class properties included in the parcel universe dataset. Would you know why a significant subset of 300 class parcels aren't included within the commercial valuation data?

> There are two main reasons I could see this being the case:
> 
>     1. Each year will only include the triad that was re-assessed, and the commercial valuations team has been working to standardize and complete this data over the last few years. Our oldest data is for the biggest triad, which means sparsity there would have an outsized impact on completeness.
>     2. The data lumps parcels together by keypin. Keypins can include multiple PINs that are all valued as a single economic unit.
