### ISSUE TITLE
2024 condo assessment data

### ISSUE THREAD

**Issue by dilemmamanagement** [ccao-data/public#23]
### General description

Can you please provide the 2024 condo assessment data in parquet format? For example, the 2024 residential assessment data is available here : https://ccao-data-public-us-east-1.s3.amazonaws.com/models/inputs/res/2024/assessment_data.parquet

### Use case

Use this data to develop a nearest neighbor algo to find comps. 

### Universe

Provide the 2024 data with all the columns and in parquet format as similar to the 2023 data: https://ccao-data-public-us-east-1.s3.amazonaws.com/models/inputs/condo/2023/assessment_data.parquet

### Unit of observation

Individual Property Index Number (PIN)

### Restrictions and exclusions

NA

### Data delivery format

Parquet

### Citation and use of Assessor data

- [X] I agree to the above terms.

**Comment by dfsnow** [comment]
Hi! Thanks for reaching out. We should have this up within the next week or two.

**Comment by dilemmamanagement** [comment]
@dfsnow thank you for your professionalism.
