### ISSUE TITLE
Bad data in pin field in Parcel Universe Open Data

### ISSUE THREAD

**Issue by rross0** [ccao-data/public#25]
### General description

I was trying to use the CCAO package's pin_format_pretty() function on the parcel universe data, but I was getting the error that there was at least one PIN that did not conform to the expected format. That PIN is "TEST000000001." If this was a test of the user, I think I passed.  I suggest removing this dummy PIN from the open data set.

### Use case

https://github.com/rross0/cc_appeals/issues/6

### Universe

One PIN

### Unit of observation

PIN

### Data delivery format

Open Data asset

### Citation and use of Assessor data

- [X] I agree to the above terms.

**Comment by dfsnow** [comment]
@rross0 This is will be resolved by https://github.com/ccao-data/data-architecture/pull/342 once PIN Universe updates during its monthly refresh. Thanks for the heads up about the test PIN.
