### ISSUE TITLE
Update README to include first, and possibly most important CCAO presentation

### ISSUE THREAD

**Issue by rross0** [ccao-data/public#26]
### General description

In 2018, I presented at Chi Hack Night. You might want to include that in the public repo README https://www.youtube.com/watch?v=T7rnr0GQoCs 

### Use case

To see where it all began

### Universe

This universe

### Unit of observation

Um.....

### Data delivery format

Other

### Citation and use of Assessor data

- [X] I agree to the above terms.

**Comment by dfsnow** [comment]
Added! Sorry for the omission.

**Comment by rross0** [comment]
@dfsnow you are now obligated to come to my BBQ.
