### ISSUE TITLE
Junior DS JD

### ISSUE THREAD

**Issue by rross0** [ccao-data/public#28]
### General description

The job description you used for Junior Data Scientists

### Use case

I want to hire a Jr Data Scientist for https://github.com/MTA-MD-OPM 

### Universe

One JD

### Unit of observation

A JD

### Restrictions and exclusions

No other JDs

### Data delivery format

Other

### Citation and use of Assessor data

- [X] I agree to the above terms.

**Comment by rross0** [comment]
@wrridgeway @dfsnow

**Comment by ccao-jardine** [comment]
I'm neither @wrridgeway nor @dfsnow, but hilariously, the PDs actually got scraped and put [here].(https://bigdatakb.com/cook-county-offices-under-the-president-junior-data-scientist-assessors-office-chicago-il-united-states-bigdatakb-com-2023-01-19/)

It stripped a URL about our [benefits package](https://www.cookcountyil.gov/sites/g/files/ywwepo161/files/documents/2022-11/OE%202023%20Employee%20Benefits%20Overview_FINAL%20Links.pdf). 

That help?

**Comment by rross0** [comment]
Thanks! Though I really **was** looking forward to hearing from one of those two.

**Comment by rross0** [comment]
@ccao-jardine lol jk thanks youre awesome
