### ISSUE TITLE
Investment rating in commercial valuation data

### ISSUE THREAD

**Issue by framoutar** [ccao-data/public#31]
### General description

Hello - 

I hope this message finds you well. Can you please let me know where the Investment Rating (i.e. A/B/C/D) variable in the [Commercial Valuation Data](https://datacatalog.cookcountyil.gov/Property-Taxation/Assessor-Commercial-Valuation-Data/csik-bsws/about_data) comes from? 

Thank you!

fern

### Use case

n/a

### Universe

n/a

### Unit of observation

n/a

### Restrictions and exclusions

n/a

### Data delivery format

Other

### Citation and use of Assessor data

- [X] I agree to the above terms.

**Comment by wrridgeway** [comment]
Hey @framoutar. These ratings are determined internally by CCAO commercial valuation analysts.
