### ISSUE TITLE
Spreadsheet containing skills matrix

### ISSUE THREAD

**Issue by rross0** [ccao-data/public#33]
### General description

In [this archived repo's README there is an image of an excel spreadsheet](https://gitlab.com/ccao-data-science---modeling/people/talent#core-competencies). I was hoping you would be able to locate and share that .xlsx file. I understand that its old and possibly lost to the ether. 

### Use case

I'd like to use it as a reference to develop a skill matrix for my Data Science team at the MTA.

### Universe

A .xlsx file.

### Unit of observation

A .xlsx file.

### Data delivery format

XLSX

### Citation and use of Assessor data

- [X] I agree to the above terms.

**Comment by dfsnow** [comment]
I looked all over the usual spots, but I think you're right that the original source of the skills matrix is lost to the ether. Sorry @rross0.

**Comment by rross0** [comment]
@dfsnow no problem, it happens. My bad for not putting it in GitLab way back when.
