### ISSUE TITLE
GitLab #22: Publish data to enable automatic TrueRoll Updates

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/public#5]
### General description

TrueRoll is a vendor for the Cook County Assessor's Office. The service that we provide the Assessor's Office requires us to ingest data from our client. In order to provide a higher level of service to the CCAO, we would like to automate this process. Automating this handoff will help us provide more accurate and timely data for the CCAO while reducing the time and attention required of CCAO staff. 

Our data standard is define by [this document](https://docs.google.com/spreadsheets/d/1ZXqeN6ANuxGbKNq2kapTTwccCYotvt_9-kHeHXAe2Ps/edit?usp=sharing) (this document is secured - only select CCAO staff will be given read access). Ideally, the CCAO would make these tables available in exactly the format described. We can make note of where that is not possible, and make reasonable accommodations. We suggest either making this data available via secure APIs, or by publishing private data on the Cook County Open Data portal.

Please direct communication on this topic to @rross0 as well as [Matt Amann](https://github.com/freepour) (matt@trueroll.io). We hope to complete this work before the CCAO needs to take action on the annual senior exemption renewal, which typically happens in December. 

Thank you for your attention to this matter. We look forward to service your office through better data integration.

**Comment by rross0** [comment]
Hey all, any progress on this request? December is fast approaching.

**Comment by ccao-jardine** [comment]
Hey, hard to believe December is almost upon us. We'd be very happy to build out an API for efficient data delivery if that's the best solution as determined by our Chief Operations Officer, who is the point of contact and decisionmaker on data sharing for this existing contract.

So, maybe we'll get to work together closely in the future! Until then, it looks like a lot of this can be combined from public [open data assets](https://datacatalog.cookcountyil.gov/stories/s/9bqn-cfsv) (Characteristics data, Parcel Sales, and Parcel Addresses) which are are refreshed periodically. For exemption data, the [ptaxsim](https://github.com/ccao-data/ptaxsim#database-installation) database has exemption data in the `pin` table, albeit not up to date.

**Comment by rross0** [comment]
Agreed about the elements that can be gathered from the Open Data Portal. What about the remaining elements, specifically the exemptions each parcel is receiving?

**Comment by rross0** [comment]
@ccao-jardine can you either set up a meeting with, or provide the contact information for your COO?

**Comment by ccao-jardine** [comment]
Someone in our office will be in touch. I lam keeping this issue closed as this is not a public data request. Again, perhaps we’ll get to work together on an efficient delivery system to accomplish our shared goal of effective exemption administration for Cook County property taxpayers.
