### ISSUE TITLE
Data request on behalf of Broadview

### ISSUE THREAD

**Issue by ccao-jardine** [ccao-data/public#7]
### General description

Original request:

> 1. A list of businesses in Broadview that have appealed at the BOR
> 2. An analysis of how much of the tax base in Broadview is in/out of the TIF

For 1, let's produce a flat file with one row per PIN:

- Universe: all class 3 and 5 PINs with a property location address in Broadview, and which have filed a TY2022 appeal with the Board of Review. Could use its [Open Data](https://datacatalog.cookcountyil.gov/Property-Taxation/Board-of-Review-Appeal-Decision-History/7pny-nedm/data)
- Columns: PIN, 3 digit class, property location address, taxpayer name, and all columns from the Board of Review decision history dataset

For 2, let's produce four numbers using TY2022 data, either as a flat file or just pasted here as a comment:

- For all PINs in Broadview: N PINs, sum AV
- For PINs that are both in Broadview and are also in a TIF in most recent tax year available: N PINs, sum AV

### Use case

Data request on behalf of Broadview, via Director of Commercial Outreach. 

### Universe

For ease of analysis, let's presume Broadview = Village of Broadview. 

### Unit of observation

See above.

### Restrictions and exclusions

See above.

### Data delivery format

XLSX

### Citation and use of Assessor data

- [X] I agree to the above terms.

**Comment by wrridgeway** [comment]
[part 1](https://github.com/ccao-data/public/files/12778222/pdr-007.xlsx)

part 2: all classes, tax year 2022

in_tif | parcels | ccao_av | bor_av
-- | -- | -- | --
No | 3005 | 100367191 | 99354911
Yes | 331 | 12298899 | 11895211
  | 3336 | 112666090 | 111250122

lemme know what needs polishing

**Comment by ccao-jardine** [comment]
Looks great. Thanks!
